# Generated by Django 3.2.16 on 2022-12-07 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_init_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='course',
        ),
        migrations.AddField(
            model_name='lessons',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.courses'),
            preserve_default=False,
        ),
    ]
