# Generated by Django 3.2.16 on 2022-12-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_created_lessons'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachersCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_first', models.CharField(max_length=100, verbose_name='Name')),
                ('name_second', models.CharField(max_length=100, verbose_name='Surname')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('deleted', models.BooleanField(default=False)),
                ('course', models.ManyToManyField(to='mainapp.Courses')),
            ],
        ),
    ]
