# Generated by Django 3.2.16 on 2022-12-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_init_modification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='preview',
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(default='Unknown author', max_length=50, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.CharField(max_length=150, null=True, verbose_name='Preview'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_url',
            field=models.CharField(default='no_image.svg', max_length=150, null=True, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.CharField(default='unknown_source', max_length=55, verbose_name='Source name'),
        ),
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.CharField(default='no_url', max_length=255, verbose_name='Source'),
        ),
    ]
