# Generated by Django 3.2.16 on 2022-12-12 11:44
# its data migration


from django.db import migrations


def forward_func(apps, schema_editor):
    print(f'{apps = }', apps.__class__)
    print(f'{schema_editor = }')

    Teachers = apps.get_model("mainapp", 'TeachersCourse')
    teachers_data = (
        ('Герасим', 'Нечипарукошвили', "1991-11-11", (3, 5)),
        ('Андрей', 'Уважаемый', "1988-05-24", (1, 6)),
        ('Сергей', 'Трудовой', "1979-01-30", (1, 5, 7)),
        ('Василий', 'Василевский', "1990-07-17", (3, 2, 8)),
        ('Валерий', 'Валерьев', "1999-05-19", (4, 6, 2)),
        ('Семен', 'Садачевич', "1997-11-05", (7, 1, 8)),
        ('Абстрактный', 'Чувак', "1993-09-25", (5, 4, 1)),
    )

    Teachers.objects.bulk_create(
        [Teachers(
            id=idx,
            name_first=teacher[0],
            name_second=teacher[1],
            birthday=teacher[2])
            for idx, teacher in enumerate(teachers_data, 1)]
    ),

    for teacher in teachers_data:
        Teachers.objects.filter(name_first=teacher[0])[0].course.set(teacher[3])

    # Teachers.objects.create(
    #     name_first='Авшалом', name_second='Цигельман', birthday='1977-06-29',  # course=[3, 4]
    # )


def reverse_func(apps, schema_editor):
    Teachers = apps.get_model('mainapp', 'TeachersCourse')
    Teachers.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_lessons_data_migration'),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func),
    ]
