# Generated by Django 3.2.16 on 2022-12-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_created_rating_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursefeedback',
            options={'verbose_name': 'CourseFeedback', 'verbose_name_plural': 'CourseFeedbacks'},
        ),
    ]
