from mainapp.views.auth import *
from mainapp.views.contacts import *
from mainapp.views.courses import *
from mainapp.views.doc_site import *
from mainapp.views.google_redirect import *
from mainapp.views.index import *
from mainapp.views.news import *
from mainapp.views.log_viewer import *
from mainapp.views.errors_handlers import *
